wandb_version: 1

env_tag:
  desc: null
  value: ImmortalSufferingEnv
max_steps:
  desc: null
  value: 100000
max_ep_len:
  desc: null
  value: 1000
update_timestep:
  desc: null
  value: 4000
K_epochs:
  desc: null
  value: 10
eps_clip:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.99
lr_actor:
  desc: null
  value: 0.0003
lr_critic:
  desc: null
  value: 0.001
action_std:
  desc: null
  value: 0.6
action_std_decay_rate:
  desc: null
  value: 0.05
min_action_std:
  desc: null
  value: 0.1
action_std_decay_freq:
  desc: null
  value: 250000
save_model_freq:
  desc: null
  value: 20000
mini_batch_size:
  desc: null
  value: 64
seed:
  desc: null
  value: 42
reward_shaping:
  desc: null
  value:
    w_progress: 1.0
    w_time: 0.001
    w_damage: 0.05
    w_not_actionable: 0.01
    terminal_bonus: 1.0
    terminal_failure_penalty: 1.0
    clip: 5.0
resume:
  desc: null
  value: true
checkpoint:
  desc: null
  value: /root/libimmortal/src/libimmortal/samples/PPO/checkpoints/PPO_ImmortalSufferingEnv_42_13400.pth
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1767509357
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      - 61
      4: 3.10.12
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
