wandb_version: 1

world_size:
  desc: null
  value: 4
num_envs:
  desc: null
  value: 2
update_timestep:
  desc: null
  value: 4000
horizon_per_env:
  desc: null
  value: 2000
max_steps:
  desc: null
  value: 200000
seed:
  desc: null
  value: 42
gamma:
  desc: null
  value: 0.99
eps_clip:
  desc: null
  value: 0.2
k_epochs:
  desc: null
  value: 10
lr_actor:
  desc: null
  value: 0.0001
lr_critic:
  desc: null
  value: 0.0002
mini_batch_size:
  desc: null
  value: 256
max_ep_len:
  desc: null
  value: 1000
reward_scaling:
  desc: null
  value: false
w_progress:
  desc: null
  value: 100.0
w_time:
  desc: null
  value: 0.02
w_damage:
  desc: null
  value: 0.1
w_not_actionable:
  desc: null
  value: 0.01
terminal_bonus:
  desc: null
  value: 6.0
reward_clip:
  desc: null
  value: 10.0
success_if_raw_reward_ge:
  desc: null
  value: 1.0
time_limit:
  desc: null
  value: 300.0
success_speed_bonus:
  desc: null
  value: 3.0
no_graphics:
  desc: null
  value: false
time_scale:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1768185937
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 61
      4: 3.10.12
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
