_wandb:
    value:
        cli_version: 0.24.0
        e:
            7a6v9d5hs4u83n41onq1aek4cqerqhj2:
                args:
                    - --port
                    - "17005"
                    - --port_stride
                    - "200"
                    - --max_ep_len
                    - "1500"
                    - --update_timestep
                    - "6000"
                    - --max_steps
                    - "1000000"
                    - --save_model_freq
                    - "50000"
                    - --wandb
                    - --seed
                    - "42"
                codePath: src/libimmortal/samples/PPO/train.py
                codePathLocal: src/libimmortal/samples/PPO/train.py
                cpu_count: 14
                cpu_count_logical: 28
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2011876704256"
                        used: "449836085248"
                email: mjkmszr0613@gmail.com
                executable: /usr/local/bin/python3.10
                git:
                    commit: 7036729fe247b100e1fc393bcf471047ce896143
                    remote: https://github.com/Mjk-123/libimmortal.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-70668b32-0826-9e5e-887f-17dda08dfb01
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-f331416d-526f-cefe-806c-c7a74da72cd5
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-7a43cd08-6d5f-c01c-9357-2a3f5ca03e3a
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-cbd553ac-de0a-2c92-45c2-62618395ff83
                host: 987ea6967769
                memory:
                    total: "67071143936"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /root/libimmortal/./src/libimmortal/samples/PPO/train.py
                python: CPython 3.10.12
                root: /root/libimmortal
                startedAt: "2026-01-21T14:09:13.038318Z"
                writerId: 7a6v9d5hs4u83n41onq1aek4cqerqhj2
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
K_epochs:
    value: 10
action_std:
    value: 0.6
action_std_decay_freq:
    value: 250000
action_std_decay_rate:
    value: 0.05
base_step:
    value: 0
ddp_world_size:
    value: 4
env_tag:
    value: ImmortalSufferingEnv
eps_clip:
    value: 0.2
gamma:
    value: 0.99
lr_actor:
    value: 0.0001
lr_critic:
    value: 0.0002
max_env_restarts:
    value: 20
max_ep_len:
    value: 1500
max_steps:
    value: 1000000
min_action_std:
    value: 0.1
mini_batch_size:
    value: 64
no_graphics:
    value: false
port_stride:
    value: 200
reward_clip:
    value: 15
reward_scaling:
    value: false
save_model_freq:
    value: 50000
scaler_clip:
    value: 5
seed:
    value: 42
terminal_bonus:
    value: 4
unity_timeout_wait:
    value: 120
update_timestep:
    value: 6000
w_acc:
    value: 1
w_damage:
    value: 0.05
w_not_actionable:
    value: 0.05
w_progress:
    value: 100
w_time:
    value: 0.02
